version: '3'

services:
    news_api:
      build: .
      container_name: news_api
      entrypoint: ./entrypoint.sh
      volumes:
        - .:/usr/src/app/
      ports:
        - "8000:8000"
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
      depends_on:
        - db
        - redis
    celery:
      build: .
      command: celery -A news_api worker -l info
      volumes:
        - .:/usr/src/app/
#      environment:
#        - CELERY_BROKER_URL=redis://redis:6379
#        - CELERY_RESULT_BACKEND=redis://redis:6379
      depends_on:
        - news_api
        - redis
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_HOST=db
        - POSTGRES_DB=news_postgresql
        - POSTGRES_USER=news_db
        - POSTGRES_PASSWORD=news_db
    redis:
      image: redis:alpine

#    celery-beat:
#      build:
#        context: .
#      command: celery -A news_api beat -l info
#      volumes:
#        - .:/usr/src/
#      depends_on:
#        - db
#        - redis

