version: '3'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_HOST=db
        - POSTGRES_DB=news_postgresql
        - POSTGRES_USER=news_db
        - POSTGRES_PASSWORD=news_db
    api:
      build: .
      entrypoint: ./entrypoint.sh
      volumes:
        - .:/usr/src/
      ports:
        - "8000:8000"
      depends_on:
        - db

