# Generated by Django 3.2.4 on 2021-06-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_news_amount_of_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="amount_of_votes",
            field=models.IntegerField(null=True),
        ),
    ]
