# Generated by Django 3.2.4 on 2021-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_news_amount_of_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
