# Generated by Django 3.2.4 on 2021-06-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_news_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
