# Generated by Django 3.2.4 on 2021-06-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('link', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('amount_of_votes', models.IntegerField()),
                ('author_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.news')),
            ],
        ),
    ]
