# Generated by Django 3.2.4 on 2021-06-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='amount_of_votes',
            field=models.BigIntegerField(),
        ),
    ]
